// <auto-generated />
using System;
using Infrastruture;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastruture.Migrations
{
    [DbContext(typeof(ServiceProposalContext))]
    [Migration("20250907173529_configuration_to_be_fast")]
    partial class configuration_to_be_fast
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CustomerId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Customer", (string)null);

                    b.HasData(
                        new
                        {
                            CustomerId = new Guid("690c6507-1c3b-4e84-a77e-8779fbba038d"),
                            Address = "rua",
                            DateCreation = new DateTime(2025, 10, 1, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            DateModification = new DateTime(2025, 10, 1, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Email = "gustavo@gmail.com",
                            Name = "gustavo",
                            PhoneNumber = "12312312312"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ProductTypeId")
                        .HasColumnType("uuid");

                    b.HasKey("ProductId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ProductTypeId");

                    b.ToTable("Product", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("50beec7c-b8f6-4edb-9730-6517fdf64b2f"),
                            DateCreation = new DateTime(2025, 10, 1, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            DateModification = new DateTime(2025, 10, 1, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "cobertura bronze com 50 hospitais",
                            Name = "cobertura bronze",
                            Price = 100m,
                            ProductTypeId = new Guid("0fa7d783-e5b6-4317-ae7e-e932d1a8d92b")
                        });
                });

            modelBuilder.Entity("Domain.Entities.ProductType", b =>
                {
                    b.Property<Guid>("ProductTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("ProductTypeId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ProductType", (string)null);

                    b.HasData(
                        new
                        {
                            ProductTypeId = new Guid("0fa7d783-e5b6-4317-ae7e-e932d1a8d92b"),
                            DateCreation = new DateTime(2025, 10, 1, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            DateModification = new DateTime(2025, 10, 1, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "seguro de via cobertura media",
                            Name = "seguro de vida"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Proposal", b =>
                {
                    b.Property<Guid>("ProposalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<long>("ProposalNumber")
                        .HasColumnType("bigint");

                    b.Property<int>("ProposalStatusId")
                        .HasColumnType("integer");

                    b.HasKey("ProposalId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProposalNumber")
                        .IsUnique();

                    b.HasIndex("ProposalStatusId");

                    b.ToTable("Proposal", (string)null);

                    b.HasData(
                        new
                        {
                            ProposalId = new Guid("cd8b89cc-92b3-4a3b-9fe4-ef2f819c9a1d"),
                            CustomerId = new Guid("690c6507-1c3b-4e84-a77e-8779fbba038d"),
                            DateCreation = new DateTime(2025, 10, 1, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            DateModification = new DateTime(2025, 10, 1, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            ProductId = new Guid("50beec7c-b8f6-4edb-9730-6517fdf64b2f"),
                            ProposalNumber = 1L,
                            ProposalStatusId = 0
                        });
                });

            modelBuilder.Entity("Domain.Entities.ProposalStatus", b =>
                {
                    b.Property<int>("StatusSystemId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("StatusSystemId");

                    b.HasIndex("Description")
                        .IsUnique();

                    b.ToTable("ProposalStatus", (string)null);

                    b.HasData(
                        new
                        {
                            StatusSystemId = 0,
                            DateCreation = new DateTime(2025, 10, 1, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            DateModification = new DateTime(2025, 10, 1, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Analysing"
                        },
                        new
                        {
                            StatusSystemId = 2,
                            DateCreation = new DateTime(2025, 10, 1, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            DateModification = new DateTime(2025, 10, 1, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Rejected"
                        },
                        new
                        {
                            StatusSystemId = 1,
                            DateCreation = new DateTime(2025, 10, 1, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            DateModification = new DateTime(2025, 10, 1, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Approved"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.HasOne("Domain.Entities.ProductType", "ProductType")
                        .WithMany()
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("Domain.Entities.Proposal", b =>
                {
                    b.HasOne("Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.ProposalStatus", "ProposalStatus")
                        .WithMany()
                        .HasForeignKey("ProposalStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Product");

                    b.Navigation("ProposalStatus");
                });
#pragma warning restore 612, 618
        }
    }
}
