# build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ./src/ContractingService/APIContracting/APIContracting.csproj ./APIContracting/
COPY ./src/ContractingService/Service/Service.csproj ./Service/
COPY ./src/ContractingService/Domain/Domain.csproj ./Domain/
COPY ./src/ContractingService/Infrastructure/Infrastructure.csproj ./Infrastructure/

RUN dotnet restore ./APIContracting/APIContracting.csproj

COPY ./src/ContractingService/ .

RUN dotnet publish ./APIContracting -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "APIContracting.dll"]
