version: "3.9"

services:

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: servicecontracting
    ports:
      - "5432:5432"
    networks:
      - contracting-proposal
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  service-contracting: #consumer
    build:
      context: .
      dockerfile: Dockerfile
    image: service-contracting:1.7
    container_name: service-contracting
    ports:
      - "8081:8080"
    networks:
      - contracting-proposal
    depends_on:
      postgres:
        condition: service_healthy


networks:
  contracting-proposal:

volumes:
  postgres-data:
